### ISSUE TITLE
Error converting installer script compatible with macOS

### ISSUE THREAD

**Issue by fragm3** [fossasia/pslab-desktop#231]
I am trying to convert the installer script compatible with macOS. I am getting this error:
<img width="957" alt="Screenshot 2019-04-12 at 1 24 24 AM" src="https://user-images.githubusercontent.com/18073126/55988580-dbf1a100-5cc1-11e9-86d0-1953270b1d67.png">

Any help would be appreciated

**Comment by fragm3** [comment]
@CloudyPadmal

**Comment by orangecms** [comment]
#568 / `c979fc8f9240fea1b52faaa7d2d43a8b06be3b8a` has added a build script for the desktop app for macOS.

This issue here belongs to https://github.com/fossasia/pslab-python now that the desktop app has been decoupled from it.

Suggested solution:
To install the library system-wide, prefer to use the system's packaging tool. There is a package now available in AUR for Arch Linux, for example. Otherwise, you can keep it in the home directory and use any of the Python tools that set the necessary environment variables or set them directly. See also https://realpython.com/lessons/module-search-path/.
