### ISSUE TITLE
Features specific to internal phone sensors can be removed from the pslab-desktop roadmap

### ISSUE THREAD

**Issue by nielek2** [fossasia/pslab-desktop#651]
Feature | Description | Status
-- | -- | --
Lux Meter | Measures the ambient light intensity |  
Barometer | Measures the Pressure |  
Accelerometer | Measures the acceleration of the device |  
Gyrometer | Measures the rate of rotation |  
Compass | Measures the absolute rotation relative to earth magnetic poles

Or is there the plan to implement this as hardware sensors attached to the PSLab?

**Comment by mariobehling** [comment]
Yes, and these sensors should also be available through the PSLab instead of the phone on the Android app. There are two ways to use sensors on the Android app a) the phone (which is intended for testing) and b) use all kinds of sensors through the PSLab itself which was the intention all along the way. Therefore I am closing this issue. Thanks.
