### ISSUE TITLE
Oscilloscope stops working when disabling X/Y Plot

### ISSUE THREAD

**Issue by alcorhythm** [fossasia/pslab-desktop#658]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**
Oscilloscope does not work anymore after disabling X/Y Plot.

* **If the current behavior is a bug, please provide the steps to reproduce it**
1. Go to Oscilloscope
2. Activate channels 1 and 2, observe working
3. Enable X/Y Plot
4. Disable X/Y Plot
5. Observe no longer showing any signals

* **What is the expected behavior?**
Oscilloscope should keep working after deactivating X/Y plot.

* **Please tell us about your environment:**
Windows 10

* **Other information** ( Any research that you may have done which you think is the cause of problem )
Steps to make the Oscilloscope work again: disconnect and reconnect USB.
It does not help to reset the device, exit and re-enter the Oscilloscope view or restart the desktop application.

**Comment by cynthi8** [comment]
Reproduced bug on Kubuntu 20.04. I will look into this.

**Comment by cynthi8** [comment]
Looking at the console logs which are shown with `npm start`, it doesn't seem like the Disable X/Y Plot is working properly. Even after the toggle switch is deactivated, X/Y Plot data is collected instead of the typical Oscilloscope data.

[log_during_normal_oscilloscope.txt](https://github.com/fossasia/pslab-desktop/files/5706940/log_during_normal_oscilloscope.txt)
[log_during_xy_oscilloscope.txt](https://github.com/fossasia/pslab-desktop/files/5706943/log_during_xy_oscilloscope.txt)
[log_after_xy_oscilloscope_is_deactivated.txt](https://github.com/fossasia/pslab-desktop/files/5706944/log_after_xy_oscilloscope_is_deactivated.txt)
